root: "example-document/"
output: "."
css: "css/"
pandoc-filters: "filters/"
fonts: "fonts/"
graphs: "graphs/"
js: "js/"
meta: "meta/"
graphics: "pics/"
references: "refs/"
templates: "templates/"
latex: "latex"