output:
  path: path/to/output/ 
  html:
    template: templates/html # a folder containing all template data
    split-level: 4
    toc-level: 2
  latex: 
    template: template.tex
    toc-level: 2
lang: en-US
plugins:
  search
  graphs
